# Generated by Django 6.0.4 on 2026-04-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='image',
            new_name='date',
        ),
    ]
